-- MySQL Script generated by MySQL Workbench
-- Wed Jun  3 14:21:03 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Sistema_Filmoteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Sistema_Filmoteca
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `Sistema_Filmoteca` DEFAULT CHARACTER SET utf8 ;
USE `Sistema_Filmoteca` ;

-- -----------------------------------------------------
-- Table `Sistema_Filmoteca`.`Tipos_de_formatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Filmoteca`.`Tipos_de_formatos` (
  `id_tipo_formato` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo_formato` VARCHAR(50) NOT NULL,
  `descripcion_tipo_formato` VARCHAR(100) NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id_tipo_formato`),
  UNIQUE INDEX `nombre_tipo_formato_UNIQUE` (`nombre_tipo_formato` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Sistema_Filmoteca`.`Formatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Filmoteca`.`Formatos` (
  `id_formato` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_formato` INT NOT NULL,
  `nombre_formato` VARCHAR(15) NOT NULL,
  `descripcion_formato` VARCHAR(150) NOT NULL,
  `capacidad_KB` INT NOT NULL,
  `resolucion_X` INT NOT NULL,
  `resolucion_Y` INT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id_formato`),
  UNIQUE INDEX `nombre_formato_UNIQUE` (`nombre_formato` ASC) VISIBLE,
  INDEX `fk_Formatos_Tipos_de_formatos_idx` (`id_tipo_formato` ASC) VISIBLE,
  CONSTRAINT `fk_Formatos_Tipos_de_formatos`
    FOREIGN KEY (`id_tipo_formato`)
    REFERENCES `Sistema_Filmoteca`.`Tipos_de_formatos` (`id_tipo_formato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Sistema_Filmoteca`.`Películas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Filmoteca`.`Películas` (
  `id_pelicula` INT NOT NULL AUTO_INCREMENT,
  `id_formato` INT NOT NULL,
  `titulo_pelicula` VARCHAR(200) NOT NULL,
  `anio_publicacion` YEAR NOT NULL,
  `restaurado` TINYINT(1) NOT NULL,
  `stock` INT NOT NULL,
  `precio_unitario` FLOAT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id_pelicula`),
  INDEX `fk_Películas_Formatos1_idx` (`id_formato` ASC) VISIBLE,
  CONSTRAINT `fk_Películas_Formatos1`
    FOREIGN KEY (`id_formato`)
    REFERENCES `Sistema_Filmoteca`.`Formatos` (`id_formato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Sistema_Filmoteca`.`Tipos_de_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Filmoteca`.`Tipos_de_usuario` (
  `id_tipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo_usuario` VARCHAR(50) NOT NULL,
  `descripcion_tipo_usuario` VARCHAR(100) NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id_tipo_usuario`),
  UNIQUE INDEX `nombre_tipo_formato_UNIQUE` (`nombre_tipo_usuario` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Sistema_Filmoteca`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Filmoteca`.`Usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_usuario` INT NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `password_hash` VARCHAR(200) NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_Usuarios_Tipos_de_usuario1_idx` (`id_tipo_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_Tipos_de_usuario1`
    FOREIGN KEY (`id_tipo_usuario`)
    REFERENCES `Sistema_Filmoteca`.`Tipos_de_usuario` (`id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Sistema_Filmoteca`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Filmoteca`.`pedidos` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `precio_total` FLOAT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_pedidos_Usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_Usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `Sistema_Filmoteca`.`Usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Sistema_Filmoteca`.`detalles_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Filmoteca`.`detalles_pedidos` (
  `id_pedido` INT NOT NULL,
  `id_pelicula` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`id_pedido`, `id_pelicula`),
  INDEX `fk_pedidos_has_Películas_Películas1_idx` (`id_pelicula` ASC) VISIBLE,
  INDEX `fk_pedidos_has_Películas_pedidos1_idx` (`id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_has_Películas_pedidos1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `Sistema_Filmoteca`.`pedidos` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_has_Películas_Películas1`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `Sistema_Filmoteca`.`Películas` (`id_pelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Insert data
-- -----------------------------------------------------
-- Tipos de formatos
INSERT INTO Tipos_de_formatos(nombre_tipo_formato, descripcion_tipo_formato, created_by)
VALUES("Óptico", "Usa un láser para leer o grabar información.", 1),
("Cinta magnética", "Un motor desliza la cinta y el magnetismo genera corrientes eléctricas.", 1);

-- Formatos
INSERT INTO Formatos(id_tipo_formato, nombre_formato, descripcion_formato, capacidad_KB, resolucion_X, resolucion_Y, created_by)
VALUES(2, "VHS", "El primer formato de video casero", 21600, 333, 480, 1),
(2, "Betamax", "Competidor del VHS", 18000, 333, 486, 1),
(1, "LaserDisc", "Precursor del DVD", 7200, 320, 240, 1),
(1, "DVD", "Derrotó al VHS por su mayor capacidad", 4700000, 720, 480, 1),
(1, "Blu-ray", "Compitiendo con el DVD al día de hoy", 50000000, 1920, 1080, 1);

-- Películas
INSERT INTO Películas(id_formato, titulo_pelicula, anio_publicacion, restaurado, stock, precio_unitario, created_by)
VALUES(1, "Bugs Bunny's 3rd Movie: 1001 Rabbit Tales", 1981, 0, 10, 5.99, 1),
(2, "The Bugs Bunny Road-Runner Movie", 1979, 0, 3, 3.99, 1),
(3, "Looney Looney Looney Bugs Bunny Movie", 1982, 0, 5, 9.99, 1),
(4, "Space Jam", 1996, 1, 30, 15.99, 1),
(5, "Daffy Duck's Quackbusters", 1988, 1, 25, 20.99, 1);

-- Tipos de Usuario
INSERT INTO Tipos_de_usuario(nombre_tipo_usuario, descripcion_tipo_usuario, created_by)
VALUES("Usuario", "Acceso básico.", 1),
("Administrador", "Acceso total", 1);

-- Usuarios
INSERT INTO Usuarios(id_tipo_usuario, username, email, password_hash, created_by)
VALUES(2, "SuperDONO17", "donovansaez@liceovvh.cl", "JAOSF)=/JF", 1),
(1, "IncrediJavi", "javierazapata@liceovvh.cl", "nsKSJ=(/!/%", 1),
(1, "MegaDav", "davidtobar@liceovvh.cl", "NAu9!)47", 1);

-- Pedidos
INSERT INTO pedidos(id_usuario, precio_total, created_by)
VALUES(1, 19.97, 1),
(2, 15.99, 1),
(3, 26.98, 1);

-- Detalles pedidos
INSERT INTO detalles_pedidos(id_pedido, id_pelicula, cantidad)
VALUES(1, 1, 5),
(1, 2, 3),
(1, 3, 2),
(2, 4, 1),
(3, 1, 10),
(3, 5, 15);

-- -----------------------------------------------------
-- Select data
-- -----------------------------------------------------
-- 1. Mostrar nombre, email y tipo de usuario de los usuarios activos
SELECT u.username, u.email, t.nombre_tipo_usuario
FROM Usuarios u
INNER JOIN Tipos_de_usuario t
ON u.id_tipo_usuario = t.id_tipo_usuario
WHERE u.deleted = 0 AND t.deleted = 0;

-- 2. Mostrar título, año, formato, stock y precio de las películas activas, ordenados de stock menor a mayor
SELECT p.titulo_pelicula, p.anio_publicacion, f.nombre_formato, p.stock, p.precio_unitario
FROM Películas p
INNER JOIN Formatos f
ON p.id_formato = f.id_formato
WHERE p.deleted = 0 AND f.deleted = 0
ORDER BY p.stock ASC;